// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEPOaXu2MHyUZMh4wW8zhj3DLCQ-IdPkk',
    appId: '1:1074448644698:web:b9f03b7abe47f7508d3663',
    messagingSenderId: '1074448644698',
    projectId: 'uniconnect-app-c600b',
    authDomain: 'uniconnect-app-c600b.firebaseapp.com',
    storageBucket: 'uniconnect-app-c600b.firebasestorage.app',
    measurementId: 'G-M53SZPC0ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_lRcEP4CWvmA2qIkr5dpVXJoRAQoG638',
    appId: '1:1074448644698:android:a1862ecf935b2ce48d3663',
    messagingSenderId: '1074448644698',
    projectId: 'uniconnect-app-c600b',
    storageBucket: 'uniconnect-app-c600b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqK6a2B2aJf6FsUCClumRh_sOySAlUecQ',
    appId: '1:1074448644698:ios:198672158c17c62b8d3663',
    messagingSenderId: '1074448644698',
    projectId: 'uniconnect-app-c600b',
    storageBucket: 'uniconnect-app-c600b.firebasestorage.app',
    iosBundleId: 'com.example.uniConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqK6a2B2aJf6FsUCClumRh_sOySAlUecQ',
    appId: '1:1074448644698:ios:198672158c17c62b8d3663',
    messagingSenderId: '1074448644698',
    projectId: 'uniconnect-app-c600b',
    storageBucket: 'uniconnect-app-c600b.firebasestorage.app',
    iosBundleId: 'com.example.uniConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEPOaXu2MHyUZMh4wW8zhj3DLCQ-IdPkk',
    appId: '1:1074448644698:web:a665076b4c33e8248d3663',
    messagingSenderId: '1074448644698',
    projectId: 'uniconnect-app-c600b',
    authDomain: 'uniconnect-app-c600b.firebaseapp.com',
    storageBucket: 'uniconnect-app-c600b.firebasestorage.app',
    measurementId: 'G-MS8J54H68F',
  );
}
